name: Complex event
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  #event filters
  push:
  #   branches:
  #     - React_app
  #     - 'dev-*'
  # paths:
  #   - '.github/workflow/*'    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    #test
    #get code
      - name: Get code
        uses: actions/checkout@v3
        #cache content 
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-log.json') }}
    #Install depdendencies
      - name: Install dependencies
        run: npm ci
    #run lint     
      - name: Run lint   
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    #get code
      - name: Get code
        uses: actions/checkout@v3
    #Install nodejs
      - name: install nodeJs (present at ubuntu)
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-log.json') }}    
    #Install depdendencies
      - name: Install dependencies
        run: npm ci
    #run test
      - name: Runt test
        run: npm test    
  build:
    needs: test
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: install nodeJs (present at ubuntu)
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-log.json') }}    
      - name: Install dependencies
        run: npm ci 
      - name: build
        run: npm run build
      - name: publish file name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'  
      - name: artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: dist-file 
          path: dist 
  deploy:
    needs: build   
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-file 
      - name: output files 
        run: ls 
      - name: output filename
        run: echo "${{ needs.build.outputs.script-file }}"  
      - name: deploy
        run: echo "deploying ......"  



#to skip workflow execution you can add git commit -m "mesagge [skip ci]"