# This is a basic workflow to help you get started with Actions

name: Deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    #get code
      - name: Get code
        uses: actions/checkout@v3
    #Install nodejs
      - name: install nodeJs (present at ubuntu)
        uses: actions/setup-node@v3
        with:
          node-version: 18
    #Install depdendencies
      - name: Install dependencies
        run: npm ci
    #run test     
      - name: Run test   
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: install nodeJs (present at ubuntu)
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci 
      - name: build
        run: npm run build
      - name: deploy
        run: echo "Deploying ......."    


    

# Multiline Commands
# run: |
#     echo "First output"
#     echo "Second output"